[build]
  base = "frontend"
  publish = "build"
  command = "yarn build"

[[redirects]]
  from = "/api/*"
  to = "https://twoem-backend.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_BACKEND_URL = "https://twoem-backend.herokuapp.com"